# Generated by Django 3.2 on 2021-05-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('championship', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('match_date', models.DateTimeField()),
                ('home', models.CharField(max_length=100)),
                ('visitor', models.CharField(max_length=100)),
                ('score_home', models.SmallIntegerField(default=0)),
                ('score_visitor', models.SmallIntegerField(default=0)),
                ('plan', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
